name: YADRO AI Project

on:
  push:
    branches: [ master, Project_8-9 ]
#  pull_request:
#    branches: [ main, Project_8-9 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run database
        run: docker compose -f Chemical_Substructure_Search/docker-compose.yml up db -d --build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Chemical_Substructure_Search/app/requirements.txt

      - name: Run static analysis
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Run tests
        run: |
          pytest Chemical_Substructure_Search/app/substructure_search_tests.py
