name: YADRO AI Project

on:
  push:
    branches: [ master, Project_8-9 ]
#  pull_request:
#    branches: [ main, Project_8-9 ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ./Chemical_Substructure_Search
          
    steps:
      
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run containers
        run: docker compose -f docker-compose.yml up db redis celery_worker -d --build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run static analysis
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
      

      - name: Run tests
        run: |
          REDIS_HOST=localhost POSTGRES_HOST=localhost celery -A app/celery_worker.py worker --loglevel=info
          REDIS_HOST=localhost POSTGRES_HOST=localhost pytest app/substructure_search_tests.py
